<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BLRL-DL95S73" failures="3" tests="5" name="Test2" time="58.135" errors="0" timestamp="2021-08-16T11:30:10 IST">
  <testcase classname="com.sg.test.LoginTest" name="InvalidCredentailsTest" time="1.353"/>
  <testcase classname="com.sg.test.LoginTest" name="InvalidCredentailsTest" time="1.376"/>
  <testcase classname="com.sg.test.LoginTest" name="validCredentailsTest" time="3.675">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentailsTest(LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentailsTest -->
  <testcase classname="com.sg.test.LoginTest" name="validCredentailsTest" time="3.168">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentailsTest(LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentailsTest -->
  <testcase classname="com.sg.test.LoginTest" name="validCredentailsTest" time="3.433">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentailsTest(LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentailsTest -->
</testsuite> <!-- Test2 -->
